services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"     # Metro bundler
      - "19000:19000"   # Expo bundler
      - "19001:19001"   # Metro inspector (websocket)
      - "19002:19002"   # Expo DevTools web UI
      - "19006:19006"   # Expo web (if used)
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
